# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kinshuk-code-1729
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul
          plugin_habits : yes 
          plugin_habits_charts_type : chartist
          plugin_habits_from : 200
          plugin_habits_days : 21
          plugin_habits_facts : yes
          plugin_habits_charts : yes
          plugin_habits_trim : yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following
